'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,mode='diagnose',filter='all',section='',query='',limit=24,items=[],current=1,activeEntry=null,view='image',lastFocus;
let saved=new Set();const reviewed=new Set();try{saved=new Set(JSON.parse(localStorage.getItem('kw-saved-pages')||'[]').filter(n=>Number.isInteger(n)&&n>=1&&n<=2500))}catch{}
const modeInfo={model:['Search the workshop<br><span>manual.</span>','Find a fault code, repair procedure or component.','3D WORKBENCH'],diagnose:['Find the fault.<br><span>Follow the manual.</span>','Enter a monitor code or describe the machine’s symptom.','DIAGNOSIS'],repair:['Repair with<br><span>the right procedure.</span>','Find testing, adjustment, disassembly and assembly instructions.','REPAIR & TEST'],library:['The complete<br><span>shop manual.</span>','Browse every section or search all 2,500 original pages.','FULL MANUAL'],saved:['Your saved<br><span>reference pages.</span>','Bookmarks are stored on this browser and device.','SAVED PAGES']};
function tokens(s){return s.toLowerCase().replace(/[’']/g,'').split(/\s+/).filter(Boolean)}
function normalize(s){return s.toLowerCase().replace(/\s+/g,' ')}
function pretty(s){if(s.startsWith('FAILURE CODE'))return s;return s.toLowerCase().replace(/(^|[.!?]\s+)[a-z]/g,c=>c.toUpperCase()).replace(/\b(ppc|clss|komtrax|rops|pm|ls|pc)\b/gi,c=>c.toUpperCase()).replace(/^[ehsa]-\d+/i,c=>c.toUpperCase())}
function setMode(m){if($('modelWorkbench'))$('modelWorkbench').hidden=m!=='model';mode=m;filter='all';section='';query='';$('query').value='';limit=24;const info=modeInfo[m];$('title').innerHTML=info[0];$('subtitle').textContent=info[1];$('crumb').textContent=info[2];document.querySelectorAll('#modes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('quick').hidden=m==='saved';$('searchform').hidden=m==='saved';$('filters').innerHTML=(m==='diagnose'?[['all','All'],['code','Fault codes'],['symptom','Symptoms']]:m==='repair'?[['all','All'],['30','Testing & adjusting'],['50','Disassembly'],['60','Standards']]:[['all','All sections'],['90','Circuit diagrams'],['00','Safety']]).map(([v,l])=>`<button data-filter="${v}" class="${v==='all'?'selected':''}">${l}</button>`).join('');runSearch()}
function snippet(p,q){let text=p.text.replace(/\s+/g,' ').trim();const t=tokens(q);let idx=Math.max(0,...t.map(k=>text.toLowerCase().indexOf(k)));let start=Math.max(0,idx-55);return (start?'…':'')+text.slice(start,start+230)+(text.length>start+230?'…':'')}
function runSearch(){if(!data)return;query=$('query').value.trim();const ts=tokens(query);let pool=[];
 if(mode==='saved'){pool=[...saved].sort((a,b)=>a-b).map(p=>({title:'Saved source page '+(data.pages[p-1].ref||p),page:p,end:p,ref:data.pages[p-1].ref,section:data.pages[p-1].section,kind:'page'}))}
 else if(query){
  const candidates=data.entries.filter(e=>{const hay=normalize(e.title);return ts.every(t=>hay.includes(t))}).map(e=>({...e,score:100+(normalize(e.title)===normalize(query)?50:0)+(e.kind==='code'?30:0)}));
  const used=new Set(candidates.map(e=>e.page));
  for(const p of data.pages){if(used.has(p.page))continue;const h=p.search; if(ts.every(t=>h.includes(t))){let e=data.entries.findLast(e=>e.page<=p.page&&e.section===p.section);pool.push({title:e?pretty(e.title):'Manual source page',page:p.page,end:p.page,ref:p.ref,section:p.section,kind:'page',score:5+(p.section==='40'&&mode==='diagnose'?15:0),excerpt:snippet(p,query)});}}
  pool=[...candidates,...pool].sort((a,b)=>b.score-a.score||a.page-b.page);
 }else{pool=data.entries.filter(e=>mode==='diagnose'?e.section==='40'&&(e.kind==='code'||e.kind==='symptom'):mode==='repair'?['30','50','60'].includes(e.section):true)}
 if(section)pool=pool.filter(e=>e.section===section);
 if(filter!=='all')pool=pool.filter(e=>['code','symptom'].includes(filter)?e.kind===filter:e.section===filter);
 items=pool;$('resultCount').textContent=`${pool.length.toLocaleString()} ${query?'matches':'topics'}`;
 $('scope').hidden=!section;$('scope').textContent=section?`${section} · ${data.sections[section]} — ${query?'matching pages':'browse this section'}`:'';
 document.querySelectorAll('#sections button').forEach(b=>b.classList.toggle('active',b.dataset.section===section));renderResults();
}
function renderResults(){const visible=items.slice(0,limit);$('results').innerHTML=visible.map((e,i)=>`<button class="card" data-result="${i}"><span class="tag ${esc(e.kind)}">${e.kind==='code'?'FAULT CODE':e.kind==='symptom'?'SYMPTOM DIAGNOSIS':e.kind==='page'?'SOURCE PAGE':esc(data.sections[e.section]||'MANUAL').toUpperCase()}</span><h3>${esc(pretty(e.title))}</h3>${e.excerpt?`<p class="excerpt">${esc(e.excerpt)}</p>`:''}<span class="meta"><b>${esc(e.ref||'Cover / index')}</b><span>PDF page ${e.page}${e.end>e.page?' · '+(e.end-e.page+1)+' pages':''}</span></span></button>`).join('')||`<div class="empty">${mode==='saved'?'No saved pages yet. Open a source page and select Save page.':query?'No matches. Try the monitor code exactly as displayed, or a simpler term such as “engine”, “swing” or “pump”.':'No topics in this selection. Choose another filter.'}</div>`;$('more').hidden=items.length<=limit}
function openReader(page,entry=null){if(!data)return;lastFocus=document.activeElement;activeEntry=entry;view='image';$('zoom').value='100';$('pageImage').style.width='100%';$('pageImage').style.maxWidth='1000px';if(!$('reader').open)$('reader').showModal();showPage(page);setView('image')}
function showPage(page){page=Number(page);if(!Number.isInteger(page)||page<1||page>data.total)return;current=page;const p=data.pages[page-1];$('readerTitle').textContent=activeEntry?pretty(activeEntry.title):'Source page '+(p.ref||page);$('readerSection').textContent=(p.section?p.section+' · '+data.sections[p.section]:'SHOP MANUAL').toUpperCase();$('pageInput').value=page;$('pageRef').textContent=p.ref?'Manual '+p.ref:'';$('pageText').textContent=p.text||'This page contains no extracted text. Read the original page image or PDF.';$('pageImage').alt=`Original manual PDF page ${page}${p.ref?', section page '+p.ref:''}`;$('imageError').hidden=true;$('pageImage').hidden=false;$('pageImage').hidden=true;WorkshopAssets.page(page).then(url=>{if(current===page){$('pageImage').src=url;$('pageImage').hidden=false}}).catch(()=>{if(current===page){$('imageError').hidden=false}});$('pdfLink').href=`pdf/${Math.floor((page-1)/50)+1}.pdf#page=${(page-1)%50+1}`;$('pdfLink').title='Original-resolution PDF, 50-page part';$('prev').disabled=page===1;$('next').disabled=page===data.total;$('sourceLabel').textContent=`SEN06701-C0 · PDF ${page} / ${data.total} · ${p.ref||'Front matter'}`;const inProcedure=activeEntry&&activeEntry.end>activeEntry.page;$('procedureStrip').hidden=!inProcedure;$('procedureStrip').textContent=inProcedure?`Topic: PDF pages ${activeEntry.page}–${activeEntry.end}. Read the complete procedure, including cautions, tools and diagrams. ${[...reviewed].filter(n=>n>=activeEntry.page&&n<=activeEntry.end).length} of ${activeEntry.end-activeEntry.page+1} pages reviewed this session.`:'';updatePageButtons();$('reader').querySelector('.reader-body').scrollTop=0}
function updatePageButtons(){$('bookmark').textContent=saved.has(current)?'Page saved':'Save page';$('bookmark').classList.toggle('reviewed',saved.has(current));$('reviewed').textContent=reviewed.has(current)?'Page reviewed':'Mark page reviewed';$('reviewed').classList.toggle('reviewed',reviewed.has(current))}
function setView(v){view=v;$('imagePane').hidden=v!=='image';$('pageText').hidden=v!=='text';$('zoomLabel').hidden=v!=='image';$('imageTab').classList.toggle('selected',v==='image');$('textTab').classList.toggle('selected',v==='text')}
$('searchform').addEventListener('submit',e=>{e.preventDefault();limit=24;runSearch()});let searchTimer;$('query').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{limit=24;runSearch()},250)});
$('modes').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b)setMode(b.dataset.mode)});
$('sections').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b){setMode('library');section=b.dataset.section;runSearch()}});
$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;limit=24;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('selected',x===b));runSearch()}});
$('quick').addEventListener('click',e=>{const b=e.target.closest('[data-q]');if(b){$('query').value=b.dataset.q;limit=24;runSearch()}});
$('results').addEventListener('click',e=>{const b=e.target.closest('[data-result]');if(b){const entry=items[Number(b.dataset.result)];openReader(entry.page,entry)}});
$('more').onclick=()=>{limit+=24;renderResults()};$('close').onclick=()=>$('reader').close();$('reader').addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus()});$('prev').onclick=()=>showPage(current-1);$('next').onclick=()=>showPage(current+1);$('pageInput').addEventListener('change',()=>{const n=Number($('pageInput').value);if(Number.isInteger(n)&&n>=1&&n<=2500)showPage(n);else $('pageInput').value=current});$('reader').addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();showPage(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();showPage(current-1)}});
$('imageTab').onclick=()=>setView('image');$('textTab').onclick=()=>setView('text');$('zoom').onchange=()=>{const z=Number($('zoom').value);$('pageImage').style.width=z+'%';$('pageImage').style.maxWidth=z===100?'1000px':'none'};$('pageImage').onerror=()=>{$('imageError').hidden=false;$('pageImage').hidden=true};$('print').onclick=()=>{setView('image');window.print()};$('bookmark').onclick=()=>{saved.has(current)?saved.delete(current):saved.add(current);try{localStorage.setItem('kw-saved-pages',JSON.stringify([...saved]))}catch{alert('Browser storage is unavailable. This bookmark will last only for this session.')}updatePageButtons();if(mode==='saved')runSearch()};$('reviewed').onclick=()=>{reviewed.has(current)?reviewed.delete(current):reviewed.add(current);showPage(current)};
function openRef(ref){const p=data?.pages.find(p=>p.ref===ref);if(p)openReader(p.page,data.entries.find(e=>e.ref===ref)||null)}$('safety').onclick=()=>openRef('00-21');$('before').onclick=()=>openRef('40-13');
Promise.resolve(window.MANUAL_DATA).then(d=>{data=d;for(const p of data.pages)p.search=normalize(p.text);$('sections').innerHTML=Object.entries(d.sections).map(([n,title])=>`<button data-section="${n}"><span>${n}</span>${esc(title)}</button>`).join('');setMode('model');const hash=location.hash.match(/^#page=(\d+)$/);if(hash)openReader(Number(hash[1]))}).catch(()=>{$('resultCount').textContent='Manual unavailable';$('results').innerHTML='<div class="empty">The manual could not load. Check your connection and reload this page.</div>'});

document.addEventListener('manual-open',e=>{if(data)openReader(e.detail.page,data.entries.find(x=>x.page===e.detail.page)||null)});
