import * as THREE from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id);
const definitions=[
{id:'engine',name:'Engine',info:'Simplified engine assembly. Open the engine layout for the actual components, then use the engine and main-pump removal procedure.',refs:[['Engine layout · 10-13',119],['Removal & installation · 50-134',1846]],explode:[-.4,2.6,0],internal:true},
{id:'pump',name:'Main hydraulic pump',info:'Approximate pump shape beside the engine. The original main-pump procedure gives the actual connections and service steps.',refs:[['Hydraulic layout · 10-55',161],['Main pump procedure · 50-327',2039]],explode:[-.2,1.3,-2.2],internal:true},
{id:'valve',name:'Control valve',info:'Simplified valve bank. The manual identifies its hydraulic components and gives removal, installation and disassembly procedures.',refs:[['Hydraulic layout · 10-55',161],['Removal & installation · 50-342',2054],['Disassembly · 50-368',2080]],explode:[1.7,2.2,-.5],internal:true},
{id:'cooling',name:'Cooling assembly',info:'Approximate radiator and cooling pack. Check the source layout for the actual arrangement and the radiator procedure before repairs.',refs:[['Cooling layout · 10-24',130],['Radiator procedure · 50-102',1814]],explode:[-1.7,1.2,1.7],internal:true},
{id:'hydraulicTank',name:'Hydraulic tank',info:'Simplified hydraulic reservoir. Its position and shape are approximate; the layout and service procedure are the repair references.',refs:[['Hydraulic layout · 10-55',161],['Tank procedure · 50-316',2028]],explode:[.9,1.5,-2.2],internal:true},
{id:'fuelTank',name:'Fuel tank',info:'Approximate fuel reservoir. Use the original tank procedure to identify pipe connections, mounting and removal requirements.',refs:[['Fuel tank procedure · 50-187',1899]],explode:[1.8,.6,-1.8],internal:true},
{id:'cab',name:'Operator cab',info:'Simplified cab, glazing and support frame. Open the original cab procedure for the actual mounting and removal instructions.',refs:[['Machine outline · 01-8',90],['Cab procedure · 50-399',2111]],explode:[.2,1.7,2.3]},
{id:'boom',name:'Boom, arm & bucket',info:'Simplified work-equipment geometry and cylinders. This model does not reproduce pin clearances, hose routes or operating reach.',refs:[['Machine outline · 01-8',90]],explode:[1.8,1.3,0]},
{id:'tracks',name:'Undercarriage & tracks',info:'Simplified track frames, rollers and shoes. The machine outline is the reference for actual overall dimensions.',refs:[['Machine outline · 01-8',90]],explode:[0,0,0]},
{id:'structure',name:'Upper structure',info:'Simplified deck, swing support and rear counterweight. Assembly spacing in this viewer is illustrative.',refs:[['Machine outline · 01-8',90]],explode:[0,.7,0]},
{id:'covers',name:'Engine covers & panels',info:'Illustrative exterior panels. Remove covers to see the major assemblies beneath them. The model is not a panel-removal sequence.',refs:[['Machine outline · 01-8',90]],explode:[-1,3.2,0]}];
const host=$('modelCanvas'),groups=new Map();let scene,camera,renderer,controls,selected='engine',auto=false;
function preview(id){const d=definitions.find(p=>p.id===id);selected=id;$('modelParts').value=id;$('assemblyTitle').textContent=d.name;$('assemblyInfo').textContent=d.info;$('assemblyRefs').replaceChildren();for(const [label,page]of d.refs){const b=document.createElement('button');b.textContent=label;b.onclick=()=>document.dispatchEvent(new CustomEvent('manual-open',{detail:{page}}));$('assemblyRefs').append(b)}for(const [key,g]of groups)g.traverse(o=>{if(o.isMesh&&o.material.emissive)o.material.emissive.setHex(key===id?0x493600:0x000000)})}
for(const d of definitions){const o=document.createElement('option');o.value=d.id;o.textContent=d.name;$('modelParts').append(o)}
$('modelParts').onchange=()=>{const id=$('modelParts').value;if(definitions.find(d=>d.id===id).internal){$('modelCovers').checked=true;applyAssembly()}preview(id)};preview(selected);
function applyAssembly(){const amount=Number($('modelExplode').value)/100;$('explodeValue').textContent=Math.round(amount*100)+'%';for(const d of definitions){const g=groups.get(d.id);if(!g)continue;g.position.set(...d.explode.map(v=>v*amount));if(d.id==='covers')g.visible=!$('modelCovers').checked}if(controls)controls.update()}
function material(color,extra={}){return new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.25,...extra})}
function group(id){const g=new THREE.Group();g.name=id;groups.set(id,g);scene.add(g);return g}
function mesh(g,geometry,mat,x=0,y=0,z=0){const m=new THREE.Mesh(geometry,mat.clone());m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;m.userData.part=g.name;g.add(m);return m}
function box(g,w,h,d,x,y,z,mat){return mesh(g,new THREE.BoxGeometry(w,h,d),mat,x,y,z)}
function cylinder(g,r,len,x,y,z,mat,axis='y'){const m=mesh(g,new THREE.CylinderGeometry(r,r,len,20),mat,x,y,z);if(axis==='z')m.rotation.x=Math.PI/2;if(axis==='x')m.rotation.z=Math.PI/2;return m}
function rod(g,start,end,r,mat){const a=new THREE.Vector3(...start),b=new THREE.Vector3(...end),m=mesh(g,new THREE.CylinderGeometry(r,r,a.distanceTo(b),16),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.sub(a).normalize());return m}
function plate(g,points,width,z,mat){const sh=new THREE.Shape();points.forEach(([x,y],i)=>i?sh.lineTo(x,y):sh.moveTo(x,y));sh.closePath();const m=mesh(g,new THREE.ExtrudeGeometry(sh,{depth:width,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.03,bevelThickness:.03}),mat);m.position.z=z-width/2;return m}
function build(){const yellow=material(0xeeba20),navy=material(0x243545),dark=material(0x29313a),metal=material(0x99a5af,{metalness:.8,roughness:.3}),engineMat=material(0x728986),blue=material(0x30728b),green=material(0x55815b),glass=material(0x73aec0,{transparent:true,opacity:.46,metalness:.1,roughness:.18});
 const tracks=group('tracks');for(const z of [-1.24,1.24]){box(tracks,3.7,.66,.64,0,.58,z,dark);for(const x of [-1.8,1.8])cylinder(tracks,.48,.65,x,.59,z,dark,'z');for(let x=-1.4;x<=1.41;x+=.56)cylinder(tracks,.3,.71,x,.39,z,metal,'z');for(let i=0;i<28;i++){const x=-1.8+i*(3.6/27);box(tracks,.105,.1,.78,x,.98,z,navy);box(tracks,.105,.1,.78,x,.12,z,navy)}for(const x of [-1.8,1.8])for(let i=0;i<10;i++){const angle=-Math.PI/2+i*Math.PI/9;const px=x+(x>0?1:-1)*Math.cos(angle)*.47,py=.56+Math.sin(angle)*.47;const t=box(tracks,.11,.12,.78,px,py,z,navy);t.rotation.z=(x>0?1:-1)*angle;} }box(tracks,2.9,.32,1.85,0,.72,0,navy);
 const frame=group('structure');cylinder(frame,1.12,.3,-.15,1.05,0,dark);box(frame,3.75,.3,2.8,-.15,1.3,0,yellow);box(frame,.48,1.08,2.7,-1.84,1.85,0,yellow);box(frame,3.6,.17,2.65,-.08,1.51,0,navy);
 const cab=group('cab');box(cab,1.3,.21,1.05,.9,1.62,.87,yellow);box(cab,1.32,.18,1.1,.9,3.08,.87,navy);for(const x of [.25,1.55])for(const z of [.33,1.4])box(cab,.065,1.42,.065,x,2.34,z,navy);box(cab,1.18,1.16,.025,.9,2.39,1.4,glass);box(cab,1.18,1.16,.025,.9,2.39,.34,glass);box(cab,.025,1.18,.95,1.55,2.39,.87,glass);box(cab,.025,1.18,.95,.25,2.39,.87,glass);box(cab,.48,.22,.47,.68,1.95,.87,dark);box(cab,.15,.68,.46,.45,2.18,.87,dark);rod(cab,[1.25,1.65,1.5],[1.25,2.75,1.5],.022,metal);box(cab,.48,.06,.48,1,1.21,1.65,dark);
 const engine=group('engine');box(engine,1.15,.72,1.1,-.91,1.97,-.05,engineMat);box(engine,1.25,.13,1.2,-.91,2.4,-.05,dark);for(let i=0;i<6;i++)box(engine,.13,.16,1.13,-1.42+i*.2,2.35,-.05,engineMat);cylinder(engine,.38,.16,-.9,1.96,-.69,metal,'z');for(let i=0;i<2;i++)cylinder(engine,.12,.35,-1.27+i*.45,1.8,.67,metal);cylinder(engine,.18,.65,-1.17,2.79,-.5,dark);cylinder(engine,.07,.75,-1.17,3.22,-.5,metal);cylinder(engine,.19,.65,-.4,2.7,.1,blue,'z');
 const pump=group('pump');cylinder(pump,.29,.56,-.94,1.96,-1.03,metal,'z');box(pump,.48,.38,.49,-.55,1.97,-1.02,blue);for(let x=-1.1;x<-.5;x+=.22)cylinder(pump,.045,.19,x,2.31,-1.07,metal);
 const cool=group('cooling');box(cool,.23,.94,1.07,-1.33,2.03,.68,dark);for(let i=0;i<10;i++)box(cool,.04,.78,.05,-1.17,2.03,.19+i*.1,metal);cylinder(cool,.31,.08,-1.08,2.04,.65,dark,'x');for(let i=0;i<5;i++){const blade=box(cool,.08,.6,.08,-1.03,2.04,.65,metal);blade.rotation.x=i*Math.PI/5;}
 const hydraulic=group('hydraulicTank');box(hydraulic,.64,.93,.72,.16,2.02,-.96,blue);cylinder(hydraulic,.09,.1,.16,2.54,-.96,metal);
 const fuel=group('fuelTank');box(fuel,.83,.72,.72,1.02,1.94,-.98,green);cylinder(fuel,.075,.1,1.02,2.36,-.98,dark);
 const valve=group('valve');box(valve,.85,.43,.67,.54,1.94,-.06,green);for(let i=0;i<6;i++){box(valve,.11,.53,.71,.2+i*.14,2.0,-.06,green);cylinder(valve,.055,.16,.2+i*.14,2.32,-.06,metal);}
 const cover=group('covers');box(cover,2.2,.16,2.48,-.7,2.61,-.03,yellow);box(cover,3.1,.86,.08,-.38,2.03,-1.41,yellow);box(cover,2.35,.91,.08,-.76,2.06,1.4,yellow);for(let i=0;i<7;i++)box(cover,.68,.025,.085,-1.03,1.82+i*.075,1.45,navy);box(cover,.7,.08,.14,-.99,2.73,-.1,dark);
 const boom=group('boom');plate(boom,[[1.08,1.57],[1.48,1.62],[2.62,3.19],[3.59,3.53],[3.53,3.87],[2.35,3.58]],.38,-.13,yellow);plate(boom,[[3.44,3.79],[3.75,3.63],[4.97,1.37],[4.71,1.13]],.3,-.13,yellow);for(const z of [-.45,.2]){rod(boom,[1.11,1.67,z],[2.53,3.19,z],.11,dark);rod(boom,[1.67,2.27,z],[2.7,3.38,z],.055,metal);}rod(boom,[2.51,3.58,-.16],[3.84,3.49,-.16],.105,dark);rod(boom,[3.17,3.54,-.16],[4.09,3.15,-.16],.047,metal);rod(boom,[4.22,2.5,.09],[4.97,1.62,.09],.075,dark);rod(boom,[4.67,1.91,.09],[5.02,1.42,.09],.035,metal);plate(boom,[[4.65,.46],[5.36,.46],[5.4,.86],[4.88,1.44],[4.54,1.11]],.9,-.13,dark);for(let i=0;i<5;i++)box(boom,.31,.09,.1,5.42,.46,-.53+i*.2,metal);for(const [x,y]of [[1.25,1.68],[3.54,3.7],[4.86,1.34]])cylinder(boom,.095,.59,x,y,-.13,metal,'z');
}
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;host.append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(40,1,.1,100);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=4;controls.maxDistance=26;controls.maxPolarAngle=Math.PI*.49;scene.add(new THREE.HemisphereLight(0xe2f1ff,0x44515d,2.4));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(5,10,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-9;key.shadow.camera.right=9;key.shadow.camera.top=9;key.shadow.camera.bottom=-9;scene.add(key);const fill=new THREE.DirectionalLight(0xa8cfff,1.5);fill.position.set(-5,4,-7);scene.add(fill);const floor=new THREE.Mesh(new THREE.CircleGeometry(12,60),new THREE.ShadowMaterial({opacity:.25}));floor.rotation.x=-Math.PI/2;floor.position.y=.045;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(20,40,0x405b70,0x2a4254);grid.position.y=.04;scene.add(grid);build();preview('engine');$('modelLoading').hidden=true;
 const reset=()=>{const f=host.clientWidth/host.clientHeight>1.5?.75:1;camera.position.set(1.3+8.5*f,1.65+4.85*f,10.8*f);controls.target.set(1.3,1.65,0);controls.update()};reset();$('modelReset').onclick=()=>{auto=false;$('modelRotate').setAttribute('aria-pressed','false');$('modelCovers').checked=false;$('modelExplode').value=0;applyAssembly();reset()};$('modelTop').onclick=()=>{camera.position.set(1.3,13,.01);controls.target.set(1.3,1.3,0);controls.update()};$('modelRotate').onclick=()=>{auto=!auto;$('modelRotate').setAttribute('aria-pressed',String(auto))};$('modelCovers').onchange=applyAssembly;$('modelExplode').oninput=applyAssembly;
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function hit(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const objects=[];for(const g of groups.values())if(g.visible)g.traverse(o=>{if(o.isMesh)objects.push(o)});return ray.intersectObjects(objects,false)[0]?.object.userData.part}let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<7){const id=hit(e);if(id)preview(id)}down=null});renderer.domElement.addEventListener('pointermove',e=>{if(e.buttons)return;const id=hit(e);$('modelHover').hidden=!id;if(id)$('modelHover').textContent=definitions.find(d=>d.id===id).name});renderer.domElement.addEventListener('pointerleave',()=>{$('modelHover').hidden=true});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('modelLoading').hidden=false;$('modelLoading').textContent='3D view interrupted. Reload to restore it. Manual links remain available.'});
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}}new ResizeObserver(resize).observe(host);resize();let visible=true;new IntersectionObserver(entries=>{visible=entries[0].isIntersecting}).observe(host);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;renderer.setAnimationLoop(()=>{if(!visible||document.hidden)return;controls.autoRotate=auto;controls.autoRotateSpeed=.8;controls.enableDamping=!reduced;controls.update();renderer.render(scene,camera)});
 // Expose only read-only diagnostics for local validation.
 window.pc210Model={parts:definitions.map(d=>({id:d.id,refs:d.refs})),get groupCount(){return groups.size},get rendererReady(){return !!renderer},select:preview};
}catch(error){console.error('3D viewer unavailable',error);$('modelLoading').hidden=false;$('modelLoading').textContent='This browser could not start the 3D view. Assembly information and original manual references remain available.';}
