'use strict';
const el=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const parts=[
{id:'lf',name:'Travel LF pressure sensor',box:[132,109,34,70],info:'The diagram identifies this sensor with GND, OUTPUT and +5V terminals. Its AMP connector is CN-P09.',pins:[['1','GND'],['2','OUTPUT'],['3','+5V']],source:'90-23 · PDF 2449 · upper-left travel sensor group'},
{id:'p09',name:'CN-P09 · AMP connector',box:[133,202,27,35],info:'Three-pin connector for the travel LF pressure sensor. The coloured segments below this connector follow the printed wire codes: B, LgY and BW. Colours are decoded using manual 00-64.',pins:[['1','GND · B (black)'],['2','OUTPUT · LgY (light green / yellow)'],['3','+5V · BW (black / white)']],source:'90-23 · PDF 2449 · connector CN-P09; colour key 00-64'},
{id:'lr',name:'Travel LR pressure sensor',box:[168,109,34,70],info:'GND, OUTPUT and +5V terminals are shown. This sensor connects through AMP connector CN-P10.',pins:[['1','GND'],['2','OUTPUT'],['3','+5V']],source:'90-23 · PDF 2449 · upper-left travel sensor group'},
{id:'p10',name:'CN-P10 · AMP connector',box:[169,202,27,35],info:'Three-pin connector for the travel LR pressure sensor. Read the original wire labels for this circuit; its wire colours are not overlaid in this version.',pins:[['1','GND'],['2','OUTPUT'],['3','+5V']],source:'90-23 · PDF 2449 · connector CN-P10'},
{id:'rf',name:'Travel RF pressure sensor',box:[204,109,34,70],info:'GND, OUTPUT and +5V terminals are shown. This sensor connects through AMP connector CN-P11.',pins:[['1','GND'],['2','OUTPUT'],['3','+5V']],source:'90-23 · PDF 2449 · upper-left travel sensor group'},
{id:'p11',name:'CN-P11 · AMP connector',box:[205,202,27,35],info:'Three-pin connector for the travel RF pressure sensor. Read the original wire labels for this circuit; its wire colours are not overlaid in this version.',pins:[['1','GND'],['2','OUTPUT'],['3','+5V']],source:'90-23 · PDF 2449 · connector CN-P11'},
{id:'rr',name:'Travel RR pressure sensor',box:[239,109,34,70],info:'GND, OUTPUT and +5V terminals are shown. This sensor connects through AMP connector CN-P12.',pins:[['1','GND'],['2','OUTPUT'],['3','+5V']],source:'90-23 · PDF 2449 · upper-left travel sensor group'},
{id:'p12',name:'CN-P12 · AMP connector',box:[240,202,27,35],info:'Three-pin connector for the travel RR pressure sensor. Read the original wire labels for this circuit; its wire colours are not overlaid in this version.',pins:[['1','GND'],['2','OUTPUT'],['3','+5V']],source:'90-23 · PDF 2449 · connector CN-P12'},
{id:'controller',name:'CH700 controller · CN-CP01',box:[282,966,794,133],info:'The CH700 controller and its CN-CP01 connector pin layout appear along the lower edge of this sheet. Zoom or open the original PDF to read individual pin and wire labels.',source:'90-23 · PDF 2449 · lower controller connector layout'},
{id:'fuse',name:'Fuse box · CN-F01',box:[1298,195,249,53],info:'Fuse connector CN-F01 appears at the upper right. Its wiring table is at the lower right. Fuse ratings and circuit names must be read from that table.',source:'90-23 · PDF 2449 · upper-right fuse connector'},
{id:'fusetable',name:'Fuse-box wiring table',box:[1428,757,183,254],info:'The original table lists fuse numbers, ratings and systems. Use this table before selecting or replacing a fuse.',source:'90-23 · PDF 2449 · lower-right wiring table'},
{id:'preheat',name:'Relay for auto preheat',box:[545,154,48,82],info:'The relay symbol and its terminal connections are shown above the main wiring paths. This outline locates the relay; it does not show whether the relay is energised.',source:'90-23 · PDF 2449 · upper relay group'},
{id:'cm1',name:'Relay for CM850 (1)',box:[596,156,49,82],info:'Relay for CM850 (1), as labelled on the source sheet. Read the source terminal markings and connected paths for test planning.',source:'90-23 · PDF 2449 · upper relay group'},
{id:'cm2',name:'Relay for CM850 (2)',box:[651,156,57,82],info:'Relay for CM850 (2), as labelled on the source sheet. Read the source terminal markings and connected paths for test planning.',source:'90-23 · PDF 2449 · upper relay group'}];
let selected=parts[0],s=1,a=0,tx=0,ty=0;const viewport=el('viewport'),sheet=el('sheet');
function node(tag,attrs){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n}
for(const p of parts){const [x,y,w,h]=p.box;const n=node('rect',{x,y,width:w,height:h,rx:2,class:'hotspot','data-id':p.id,tabindex:0,role:'button','aria-label':p.name});n.append(node('title',{}));n.firstChild.textContent=p.name;n.addEventListener('pointerenter',()=>{if(!pointers.size)select(p)});n.addEventListener('focus',()=>select(p));n.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();select(p)} });el('parts').append(n);const opt=document.createElement('option');opt.value=p.id;opt.textContent=p.name;el('component').append(opt)}
const wireDefs=[{x:141,color:'#191919'},{x:147,color:'#9adb61',mark:'#f3cc00'},{x:153,color:'#191919',mark:'#fff'}];for(const w of wireDefs){const path=`M ${w.x} 229 L ${w.x} 273`;el('wires').append(node('path',{d:path,stroke:w.color,class:'wire-base'}));if(w.mark)el('wires').append(node('path',{d:path,stroke:w.mark,class:'wire-mark'}));}
function select(p){selected=p;el('partTitle').textContent=p.name;el('partInfo').textContent=p.info;el('source').textContent='Source: '+p.source;el('component').value=p.id;el('pinList').replaceChildren();if(p.pins){const table=document.createElement('table');table.className='pins';const head=document.createElement('tr');head.innerHTML='<th scope="col">Pin</th><th scope="col">Diagram label</th>';table.append(head);for(const [pin,label] of p.pins){const tr=document.createElement('tr');for(const t of [pin,label]){const td=document.createElement('td');td.textContent=t;tr.append(td)}table.append(tr)}el('pinList').append(table)}document.querySelectorAll('.hotspot').forEach(n=>n.classList.toggle('active',n.dataset.id===p.id));el('wires').classList.toggle('selected-wire',['lf','p09'].includes(p.id));}
function rad(){return a*Math.PI/180}function rotated(x,y){const r=rad();return [x*Math.cos(r)-y*Math.sin(r),x*Math.sin(r)+y*Math.cos(r)]}function update(){sheet.style.transform=`translate(${tx}px,${ty}px) rotate(${a}deg) scale(${s})`;el('scale').textContent=Math.round(s*100)+'%';el('position').textContent=((a%360+360)%360)+'° rotation';}
function center(x,y,scale=s){s=Math.max(.08,Math.min(12,scale));const r=rotated(x,y);tx=viewport.clientWidth/2-s*r[0];ty=viewport.clientHeight/2-s*r[1];update()}
function fit(){const odd=Math.abs(a/90)%2===1;const w=odd?1190.5513:1683.7795,h=odd?1683.7795:1190.5513;center(1683.7795/2,1190.5513/2,Math.min((viewport.clientWidth-30)/w,(viewport.clientHeight-30)/h));}
function localPoint(x,y){const r=rad(),dx=(x-tx)/s,dy=(y-ty)/s;return [dx*Math.cos(r)+dy*Math.sin(r),-dx*Math.sin(r)+dy*Math.cos(r)]}
function zoomAt(scale,x=viewport.clientWidth/2,y=viewport.clientHeight/2){const p=localPoint(x,y);s=Math.max(.08,Math.min(12,scale));const r=rotated(...p);tx=x-s*r[0];ty=y-s*r[1];update()}
function rotate(delta){const p=localPoint(viewport.clientWidth/2,viewport.clientHeight/2);a+=delta;center(...p)}
el('plus').onclick=()=>zoomAt(s*1.3);el('minus').onclick=()=>zoomAt(s/1.3);el('left').onclick=()=>rotate(-90);el('right').onclick=()=>rotate(90);el('fit').onclick=fit;el('sensorView').onclick=()=>{a=0;center(198,242,Math.min(viewport.clientWidth/220,viewport.clientHeight/330))};el('focus').onclick=()=>{const [x,y,w,h]=selected.box;center(x+w/2,y+h/2,Math.max(s,Math.min(viewport.clientWidth/(w+90),viewport.clientHeight/(h+110),4)))};el('component').onchange=()=>select(parts.find(p=>p.id===el('component').value));el('colors').onchange=()=>{el('wires').style.display=el('colors').checked?'':'none'};el('hotspots').onchange=()=>sheet.classList.toggle('hide-parts',!el('hotspots').checked);
const pointers=new Map();let drag=null;function pos(e){const r=viewport.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function pinch(){const ps=[...pointers.values()];return {x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2,d:Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)}}
viewport.addEventListener('pointerdown',e=>{if(e.button&&e.button!==0)return;const p=pos(e);pointers.set(e.pointerId,p);drag={x:p.x,y:p.y,startx:p.x,starty:p.y,id:e.target.closest('[data-id]')?.dataset.id};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging')});viewport.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.size===2?pinch():null,p=pos(e);pointers.set(e.pointerId,p);if(old){const now=pinch();if(old.d>5)zoomAt(s*now.d/old.d,old.x,old.y);tx+=now.x-old.x;ty+=now.y-old.y}else if(drag){tx+=p.x-drag.x;ty+=p.y-drag.y;drag.x=p.x;drag.y=p.y}update()});function end(e){const p=pos(e);if(drag?.id&&Math.hypot(p.x-drag.startx,p.y-drag.starty)<7)select(parts.find(x=>x.id===drag.id));pointers.delete(e.pointerId);if(!pointers.size){drag=null;viewport.classList.remove('dragging')}else{const first=[...pointers.values()][0];drag={...first,startx:first.x,starty:first.y}}}viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);viewport.addEventListener('wheel',e=>{e.preventDefault();const p=pos(e);zoomAt(s*Math.exp(-e.deltaY*.0015),p.x,p.y)},{passive:false});viewport.addEventListener('keydown',e=>{if(e.target!==viewport)return;let used=true;switch(e.key){case '+':case '=':zoomAt(s*1.2);break;case '-':zoomAt(s/1.2);break;case 'ArrowLeft':tx+=40;break;case 'ArrowRight':tx-=40;break;case 'ArrowUp':ty+=40;break;case 'ArrowDown':ty-=40;break;case '0':fit();break;default:used=false}if(used){e.preventDefault();update()}});window.addEventListener('resize',fit);select(selected);fit();
